name: release upgradeable

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'version (v0.0.0)'
        required: true
        type: string

jobs:
  release:
    environment: push-upgradeable
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          repository: OpenZeppelin/openzeppelin-contracts-upgradeable
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN_UPGRADEABLE }}
          path: './upgradeable'
      - name: Run
        run: |
          pwd
          ls
          echo AA
          cd upgradeable && ls
          echo ${{ inputs.version }}
          git checkout release-v${{ inputs.version }}
          git log -1 --pretty=%B
          if git log -1 --pretty=%B | grep -q "Transpile 41e30cdee"; then
            echo "Substring found"
          else
            echo "Substring not found"
          fi
        env:
          REF: ${{ github.ref }}
          REMOTE: https://github.com/${{ github.repository }}.git
      - name: Set up environment
        uses: ./.github/actions/setup
      - run: bash scripts/git-user-config.sh
      - name: Transpile to upgradeable
        run: bash scripts/upgradeable/transpile-onto.sh ${{ github.ref_name }} origin/${{ github.ref_name }}
        env:
          SUBMODULE_REMOTE: https://github.com/${{ github.repository }}.git
      - run: git push origin ${{ github.ref_name }}
