name: Release Upgradeable

on:
  workflow_dispatch: {}

jobs:
  release-upgradeable:
    environment: push-upgradeable
    permissions:
      id-token: write  # Required for OIDC
      contents: read
    runs-on: ubuntu-latest
    env:
      VANILLA_REPO: OpenZeppelin/openzeppelin-contracts
      UPGRADEABLE_REPO: james-toussaint/openzeppelin-contracts-upgradeable # TODO: Update repo before merging
    steps:
      - run: |
          pwd
          echo "ROOT=$(pwd)" >> "$GITHUB_ENV"
          echo "VANILLA_DIR=$(pwd)/vanilla" >> "$GITHUB_ENV"
          echo "UPGRADEABLE_DIR=$(pwd)/upgradeable" >> "$GITHUB_ENV"
      - uses: actions/checkout@v5
        with:
          repository: ${{ env.VANILLA_REPO }}
          ref: ${{ github.ref }}
          path: vanilla
      - id: vanilla
        name: Get vanilla commit
        run: |
          pwd
          ls -la      
          ls -la "${VANILLA_DIR}"      
          cd "${VANILLA_DIR}"
          echo "commit=$(git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"
      - uses: actions/checkout@v5 # TODO: Remove this 2 lines before merging (used to get node 24.x from setup action)
        with:  
          path: vanilla
      - name: Set up environment
        uses: vanilla/.github/actions/setup
      - uses: actions/checkout@v5
        with:
          repository: ${{ env.UPGRADEABLE_REPO }}
          submodules: true
          token: ${{ secrets.GH_TOKEN_UPGRADEABLE }}
          ref: ${{ github.ref }}
          path: upagradeable
      - run: tree "${ROOT}"
      - run: bash "${VANILLA_DIR}/scripts/git-user-config.sh"
      - id: publish
        name: Publish
        run: bash "${VANILLA_DIR}/scripts/release/workflow/publish-upgradeable.sh"
        env:
          VANILLA_COMMIT: ${{ steps.vanilla.outputs.commit }}
      - name: Create Github Release Note
        run: bash "${VANILLA_DIR}/scripts/release/workflow/github-release-upgradeable.sh"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN_UPGRADEABLE }}
          GIT_TAG: ${{ steps.publish.outputs.git_tag }}
          ADDITIONAL_OPTION_IF_PRERELEASE: ${{ steps.publish.outputs.additional_option_if_prerelease }}
