name: release upgradeable

on:
  workflow_dispatch: {}

jobs:
  release:
    environment: push-upgradeable
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          repository: OpenZeppelin/openzeppelin-contracts-upgradeable
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN_UPGRADEABLE }}
          path: './upgradeable'
      - name: Run
        run: |
          pwd
          ls
          ls upgradeable
        env:
          REF: ${{ github.ref }}
          REMOTE: https://github.com/${{ github.repository }}.git
      - name: Set up environment
        uses: ./.github/actions/setup
      - run: bash scripts/git-user-config.sh
      - name: Transpile to upgradeable
        run: bash scripts/upgradeable/transpile-onto.sh ${{ github.ref_name }} origin/${{ github.ref_name }}
        env:
          SUBMODULE_REMOTE: https://github.com/${{ github.repository }}.git
      - run: git push origin ${{ github.ref_name }}
